apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/demo/apps/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
